version: '3.8'

services:
  website-monitor:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: ghcr.io/vveil/uptime:latest
    container_name: website-monitor
    environment:
      - WEBSITES=${WEBSITES}
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - INTERVAL=600
    restart: always
